apiVersion: v2
name: external-dns
description: external-dns + Cloudflare for Veric platform.
type: application
version: 0.1.0
appVersion: "0.15"
dependencies:
  - name: external-dns
    version: "1.15.0"
    repository: https://kubernetes-sigs.github.io/external-dns/
