{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-worker
  labels:
    {{- include "telemetry-worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "telemetry-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "telemetry-worker.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- if .Values.externalSecrets.enabled }}
          envFrom:
            - secretRef:
                name: telemetry-worker-env
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
