{{- if and .Values.enabled .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telemetry-worker
  labels:
    {{- include "telemetry-worker.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn | quote }}
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    {{- with .Values.ingress.groupName }}
    alb.ingress.kubernetes.io/group.name: {{ . | quote }}
    alb.ingress.kubernetes.io/group.order: {{ default 40 $.Values.ingress.groupOrder | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: telemetry-worker
                port:
                  number: {{ .Values.service.port }}
{{- end }}
