{{- if and .Values.enabled .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: telemetry-worker
  labels:
    {{- include "telemetry-worker.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "telemetry-worker.selectorLabels" . | nindent 6 }}
{{- end }}
