apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-foundation-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      role: arn:aws:iam::487542879472:role/eso-foundation-reader
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
