{{- if .Values.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dbt
  labels:
    {{- include "dbt.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      template:
        metadata:
          labels:
            {{- include "dbt.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          serviceAccountName: {{ .Values.serviceAccount.name }}
          containers:
            - name: dbt
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                {{- toYaml .Values.command | nindent 16 }}
              args:
                {{- toYaml .Values.args | nindent 16 }}
              env:
                {{- range $k, $v := .Values.env }}
                - name: {{ $k }}
                  value: {{ $v | quote }}
                {{- end }}
              {{- if .Values.externalSecrets.enabled }}
              envFrom:
                - secretRef:
                    name: dbt-env
              {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
{{- end }}
