{{- if and .Values.enabled .Values.ingress.enabled -}}
{{- $certArns := prepend (default (list) .Values.ingress.additionalCertArns) .Values.ingress.certificateArn -}}
{{- $hosts := prepend (default (list) .Values.ingress.additionalHosts) .Values.ingress.hostname -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  labels:
    {{- include "web.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: {{ join "," $certArns | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range $host := $hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
{{- end }}
