{{- if and .Values.enabled .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "web.selectorLabels" . | nindent 6 }}
{{- end }}
