{{- if and .Values.enabled .Values.rollout.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: web
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "web.selectorLabels" . | nindent 6 }}
  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 0
      steps:
        {{- toYaml .Values.rollout.steps | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "web.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "web.podSpec" . | nindent 6 }}
{{- end }}
