cluster-autoscaler:
  autoDiscovery:
    clusterName: veric-platform-dev # overridden per env
  awsRegion: us-west-2
  rbac:
    serviceAccount:
      create: true
      name: cluster-autoscaler-aws-cluster-autoscaler
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::381234267633:role/veric-cluster-autoscaler-veric-platform-dev"
  extraArgs:
    skip-nodes-with-system-pods: false
    skip-nodes-with-local-storage: false
    balance-similar-node-groups: true
    expander: least-waste
