enabled: true
replicaCount: 2
pdb:
  enabled: true
  minAvailable: 1
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
rds:
  ssmEndpointParam: /veric/platform-nonprod/rds/endpoint
  ssmPortParam: /veric/platform-nonprod/rds/port
  ssmDbNameParam: /veric/platform-nonprod/rds/db-name
  masterSecretName: /veric/platform-nonprod/rds/master
serviceAccount:
  name: telemetry-worker
  roleArn: arn:aws:iam::155055143405:role/veric-app-telemetry-worker-veric-platform-nonprod

externalSecrets:
  data:
    - secretKey: DATABASE_URL
      remoteKey: /veric/platform-nonprod/telemetry-worker/database-url
    - secretKey: BETTER_AUTH_SECRET
      remoteKey: /veric/platform-nonprod/telemetry-worker/better-auth-secret
